# Constants
DOTFILES="$HOME/.dotfiles"
OS=
#vim is default editor
export EDITOR="vim"

# Determine OS
if [[ "$(uname)" == "Darwin" ]]; then
  OS="Darwin"
elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
  OS="Linux"
elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]]; then
  OS="Cygwin"
fi

source $DOTFILES/git/gitprompt
source $DOTFILES/go/golangrc
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/async.zsh
source $DOTFILES/zsh/pure.zsh
source $DOTFILES/zsh/keyboardio.zsh

fpath=( "$HOME/.zfunctions" $fpath )

autoload -U compinit && compinit

#emacs mode
bindkey -e

#Always in TMUX
_not_inside_tmux() { [[ -z "$TMUX" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}

ensure_tmux_is_running

#NVM Config
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
source $DOTFILES/zsh/nvm.zsh

# Source .zshrc.work if it exists
[ -s "$HOME/.zshrc.work" ] && source $HOME/.zshrc.work

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
