DOTFILES="$HOME/.dotfiles"

#vim is default editor
export EDITOR="vim"

source $DOTFILES/bash/bash_profile
source $DOTFILES/git/gitprompt
source $DOTFILES/go/golangrc
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/async.zsh
source $DOTFILES/zsh/pure.zsh

fpath=( "$HOME/.zfunctions" $fpath )

autoload -U compinit && compinit

#emacs mode
bindkey -e

#Always in TMUX
_not_inside_tmux() { [[ -z "$TMUX" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}

ensure_tmux_is_running
