export PATH=/usr/local/bin:$PATH #Homebrew
export PATH=~/bin/:$PATH #Load bin directory
PATH=$PATH:/usr/local/sbin #RabbitMQ

source ~/.profile # Load the default
source ~/.bash_profile.work # Load the work bash_profile
